// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: hapi/annotations/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCodeLocation int32

const (
	ResponseCodeLocation_RESPONSE_CODE_LOCATION_BODY   ResponseCodeLocation = 0 // default
	ResponseCodeLocation_RESPONSE_CODE_LOCATION_HEADER ResponseCodeLocation = 1
)

// Enum value maps for ResponseCodeLocation.
var (
	ResponseCodeLocation_name = map[int32]string{
		0: "RESPONSE_CODE_LOCATION_BODY",
		1: "RESPONSE_CODE_LOCATION_HEADER",
	}
	ResponseCodeLocation_value = map[string]int32{
		"RESPONSE_CODE_LOCATION_BODY":   0,
		"RESPONSE_CODE_LOCATION_HEADER": 1,
	}
)

func (x ResponseCodeLocation) Enum() *ResponseCodeLocation {
	p := new(ResponseCodeLocation)
	*p = x
	return p
}

func (x ResponseCodeLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCodeLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_hapi_annotations_annotations_proto_enumTypes[0].Descriptor()
}

func (ResponseCodeLocation) Type() protoreflect.EnumType {
	return &file_hapi_annotations_annotations_proto_enumTypes[0]
}

func (x ResponseCodeLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCodeLocation.Descriptor instead.
func (ResponseCodeLocation) EnumDescriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

type AuthKind int32

const (
	AuthKind_AUTH_KIND_NONE             AuthKind = 0 // default
	AuthKind_AUTH_KIND_BEARER_IN_HEADER AuthKind = 1
)

// Enum value maps for AuthKind.
var (
	AuthKind_name = map[int32]string{
		0: "AUTH_KIND_NONE",
		1: "AUTH_KIND_BEARER_IN_HEADER",
	}
	AuthKind_value = map[string]int32{
		"AUTH_KIND_NONE":             0,
		"AUTH_KIND_BEARER_IN_HEADER": 1,
	}
)

func (x AuthKind) Enum() *AuthKind {
	p := new(AuthKind)
	*p = x
	return p
}

func (x AuthKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hapi_annotations_annotations_proto_enumTypes[1].Descriptor()
}

func (AuthKind) Type() protoreflect.EnumType {
	return &file_hapi_annotations_annotations_proto_enumTypes[1]
}

func (x AuthKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthKind.Descriptor instead.
func (AuthKind) EnumDescriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

type GlobalOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCodeIn ResponseCodeLocation    `protobuf:"varint,1,opt,name=response_code_in,json=responseCodeIn,proto3,enum=hapi.annotations.ResponseCodeLocation" json:"response_code_in,omitempty"`
	AuthKind       AuthKind                `protobuf:"varint,2,opt,name=auth_kind,json=authKind,proto3,enum=hapi.annotations.AuthKind" json:"auth_kind,omitempty"`
	Info           *GlobalOptions_Info     `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Servers        []*GlobalOptions_Server `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *GlobalOptions) Reset() {
	*x = GlobalOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hapi_annotations_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions) ProtoMessage() {}

func (x *GlobalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions.ProtoReflect.Descriptor instead.
func (*GlobalOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalOptions) GetResponseCodeIn() ResponseCodeLocation {
	if x != nil {
		return x.ResponseCodeIn
	}
	return ResponseCodeLocation_RESPONSE_CODE_LOCATION_BODY
}

func (x *GlobalOptions) GetAuthKind() AuthKind {
	if x != nil {
		return x.AuthKind
	}
	return AuthKind_AUTH_KIND_NONE
}

func (x *GlobalOptions) GetInfo() *GlobalOptions_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GlobalOptions) GetServers() []*GlobalOptions_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type MethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Route:
	//
	//	*MethodOptions_Get
	//	*MethodOptions_Post
	//	*MethodOptions_Delete
	//	*MethodOptions_Put
	//	*MethodOptions_Patch
	Route    isMethodOptions_Route `protobuf_oneof:"route"`
	SkipAuth bool                  `protobuf:"varint,20,opt,name=skip_auth,json=skipAuth,proto3" json:"skip_auth,omitempty"`
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hapi_annotations_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

func (m *MethodOptions) GetRoute() isMethodOptions_Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (x *MethodOptions) GetGet() string {
	if x, ok := x.GetRoute().(*MethodOptions_Get); ok {
		return x.Get
	}
	return ""
}

func (x *MethodOptions) GetPost() string {
	if x, ok := x.GetRoute().(*MethodOptions_Post); ok {
		return x.Post
	}
	return ""
}

func (x *MethodOptions) GetDelete() string {
	if x, ok := x.GetRoute().(*MethodOptions_Delete); ok {
		return x.Delete
	}
	return ""
}

func (x *MethodOptions) GetPut() string {
	if x, ok := x.GetRoute().(*MethodOptions_Put); ok {
		return x.Put
	}
	return ""
}

func (x *MethodOptions) GetPatch() string {
	if x, ok := x.GetRoute().(*MethodOptions_Patch); ok {
		return x.Patch
	}
	return ""
}

func (x *MethodOptions) GetSkipAuth() bool {
	if x != nil {
		return x.SkipAuth
	}
	return false
}

type isMethodOptions_Route interface {
	isMethodOptions_Route()
}

type MethodOptions_Get struct {
	Get string `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type MethodOptions_Post struct {
	Post string `protobuf:"bytes,2,opt,name=post,proto3,oneof"`
}

type MethodOptions_Delete struct {
	Delete string `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type MethodOptions_Put struct {
	Put string `protobuf:"bytes,4,opt,name=put,proto3,oneof"`
}

type MethodOptions_Patch struct {
	Patch string `protobuf:"bytes,5,opt,name=patch,proto3,oneof"`
}

func (*MethodOptions_Get) isMethodOptions_Route() {}

func (*MethodOptions_Post) isMethodOptions_Route() {}

func (*MethodOptions_Delete) isMethodOptions_Route() {}

func (*MethodOptions_Put) isMethodOptions_Route() {}

func (*MethodOptions_Patch) isMethodOptions_Route() {}

type ResponseCodeValueOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desc string `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	// Types that are assignable to Predefined:
	//
	//	*ResponseCodeValueOptions_IsOk
	//	*ResponseCodeValueOptions_IsInvalidInput
	//	*ResponseCodeValueOptions_IsUnauthenticated
	//	*ResponseCodeValueOptions_IsServerError
	Predefined isResponseCodeValueOptions_Predefined `protobuf_oneof:"predefined"`
}

func (x *ResponseCodeValueOptions) Reset() {
	*x = ResponseCodeValueOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hapi_annotations_annotations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCodeValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCodeValueOptions) ProtoMessage() {}

func (x *ResponseCodeValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCodeValueOptions.ProtoReflect.Descriptor instead.
func (*ResponseCodeValueOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseCodeValueOptions) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (m *ResponseCodeValueOptions) GetPredefined() isResponseCodeValueOptions_Predefined {
	if m != nil {
		return m.Predefined
	}
	return nil
}

func (x *ResponseCodeValueOptions) GetIsOk() bool {
	if x, ok := x.GetPredefined().(*ResponseCodeValueOptions_IsOk); ok {
		return x.IsOk
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsInvalidInput() bool {
	if x, ok := x.GetPredefined().(*ResponseCodeValueOptions_IsInvalidInput); ok {
		return x.IsInvalidInput
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsUnauthenticated() bool {
	if x, ok := x.GetPredefined().(*ResponseCodeValueOptions_IsUnauthenticated); ok {
		return x.IsUnauthenticated
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsServerError() bool {
	if x, ok := x.GetPredefined().(*ResponseCodeValueOptions_IsServerError); ok {
		return x.IsServerError
	}
	return false
}

type isResponseCodeValueOptions_Predefined interface {
	isResponseCodeValueOptions_Predefined()
}

type ResponseCodeValueOptions_IsOk struct {
	IsOk bool `protobuf:"varint,10,opt,name=is_ok,json=isOk,proto3,oneof"`
}

type ResponseCodeValueOptions_IsInvalidInput struct {
	IsInvalidInput bool `protobuf:"varint,11,opt,name=is_invalid_input,json=isInvalidInput,proto3,oneof"`
}

type ResponseCodeValueOptions_IsUnauthenticated struct {
	IsUnauthenticated bool `protobuf:"varint,12,opt,name=is_unauthenticated,json=isUnauthenticated,proto3,oneof"`
}

type ResponseCodeValueOptions_IsServerError struct {
	IsServerError bool `protobuf:"varint,13,opt,name=is_server_error,json=isServerError,proto3,oneof"`
}

func (*ResponseCodeValueOptions_IsOk) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsInvalidInput) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsUnauthenticated) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsServerError) isResponseCodeValueOptions_Predefined() {}

type GlobalOptions_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GlobalOptions_Info) Reset() {
	*x = GlobalOptions_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hapi_annotations_annotations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalOptions_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions_Info) ProtoMessage() {}

func (x *GlobalOptions_Info) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions_Info.ProtoReflect.Descriptor instead.
func (*GlobalOptions_Info) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GlobalOptions_Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GlobalOptions_Info) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GlobalOptions_Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GlobalOptions_Server) Reset() {
	*x = GlobalOptions_Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hapi_annotations_annotations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalOptions_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions_Server) ProtoMessage() {}

func (x *GlobalOptions_Server) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions_Server.ProtoReflect.Descriptor instead.
func (*GlobalOptions_Server) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GlobalOptions_Server) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var file_hapi_annotations_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GlobalOptions)(nil),
		Field:         71620996,
		Name:          "hapi.annotations.global_options",
		Tag:           "bytes,71620996,opt,name=global_options",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         87040365,
		Name:          "hapi.annotations.method",
		Tag:           "bytes,87040365,opt,name=method",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         17916130,
		Name:          "hapi.annotations.is_type_of_response_code",
		Tag:           "varint,17916130,opt,name=is_type_of_response_code",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ResponseCodeValueOptions)(nil),
		Field:         33878095,
		Name:          "hapi.annotations.response_code_value",
		Tag:           "bytes,33878095,opt,name=response_code_value",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         43713190,
		Name:          "hapi.annotations.method_extension_response_codes",
		Tag:           "varint,43713190,opt,name=method_extension_response_codes",
		Filename:      "hapi/annotations/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional hapi.annotations.GlobalOptions global_options = 71620996;
	E_GlobalOptions = &file_hapi_annotations_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional hapi.annotations.MethodOptions method = 87040365;
	E_Method = &file_hapi_annotations_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional bool is_type_of_response_code = 17916130;
	E_IsTypeOfResponseCode = &file_hapi_annotations_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional hapi.annotations.ResponseCodeValueOptions response_code_value = 33878095;
	E_ResponseCodeValue = &file_hapi_annotations_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool method_extension_response_codes = 43713190;
	E_MethodExtensionResponseCodes = &file_hapi_annotations_annotations_proto_extTypes[4]
)

var File_hapi_annotations_annotations_proto protoreflect.FileDescriptor

var file_hapi_annotations_annotations_proto_rawDesc = []byte{
	0x0a, 0x22, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a, 0x0d, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x50, 0x0a, 0x10, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x12, 0x37, 0x0a, 0x09,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x40, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x1a, 0x36, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x1a, 0x1a, 0x0a, 0x06, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x70,
	0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x70,
	0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x70, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x5f,
	0x61, 0x75, 0x74, 0x68, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x70,
	0x41, 0x75, 0x74, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0xda, 0x01,
	0x0a, 0x18, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x15,
	0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x0e, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x2f, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x11, 0x69, 0x73, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0d, 0x69,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0c, 0x0a, 0x0a,
	0x70, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x2a, 0x5a, 0x0a, 0x14, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f, 0x44,
	0x59, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x48, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x2a, 0x3e, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x42, 0x45, 0x41, 0x52, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x5f, 0x48, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x3a, 0x67, 0x0a, 0x0e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x84, 0xb3, 0x93, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a,
	0x5a, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xed, 0xc2, 0xc0, 0x29, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x57, 0x0a, 0x18, 0x69,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe2, 0xc1, 0xc5, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14,
	0x69, 0x73, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x3a, 0x80, 0x01, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xcf, 0xe0, 0x93, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x67, 0x0a, 0x1f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa6, 0x85, 0xec, 0x14, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x61, 0x6c, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x2f, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hapi_annotations_annotations_proto_rawDescOnce sync.Once
	file_hapi_annotations_annotations_proto_rawDescData = file_hapi_annotations_annotations_proto_rawDesc
)

func file_hapi_annotations_annotations_proto_rawDescGZIP() []byte {
	file_hapi_annotations_annotations_proto_rawDescOnce.Do(func() {
		file_hapi_annotations_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_hapi_annotations_annotations_proto_rawDescData)
	})
	return file_hapi_annotations_annotations_proto_rawDescData
}

var file_hapi_annotations_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hapi_annotations_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hapi_annotations_annotations_proto_goTypes = []interface{}{
	(ResponseCodeLocation)(0),             // 0: hapi.annotations.ResponseCodeLocation
	(AuthKind)(0),                         // 1: hapi.annotations.AuthKind
	(*GlobalOptions)(nil),                 // 2: hapi.annotations.GlobalOptions
	(*MethodOptions)(nil),                 // 3: hapi.annotations.MethodOptions
	(*ResponseCodeValueOptions)(nil),      // 4: hapi.annotations.ResponseCodeValueOptions
	(*GlobalOptions_Info)(nil),            // 5: hapi.annotations.GlobalOptions.Info
	(*GlobalOptions_Server)(nil),          // 6: hapi.annotations.GlobalOptions.Server
	(*descriptorpb.FileOptions)(nil),      // 7: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),    // 8: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 9: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 10: google.protobuf.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),     // 11: google.protobuf.FieldOptions
}
var file_hapi_annotations_annotations_proto_depIdxs = []int32{
	0,  // 0: hapi.annotations.GlobalOptions.response_code_in:type_name -> hapi.annotations.ResponseCodeLocation
	1,  // 1: hapi.annotations.GlobalOptions.auth_kind:type_name -> hapi.annotations.AuthKind
	5,  // 2: hapi.annotations.GlobalOptions.info:type_name -> hapi.annotations.GlobalOptions.Info
	6,  // 3: hapi.annotations.GlobalOptions.servers:type_name -> hapi.annotations.GlobalOptions.Server
	7,  // 4: hapi.annotations.global_options:extendee -> google.protobuf.FileOptions
	8,  // 5: hapi.annotations.method:extendee -> google.protobuf.MethodOptions
	9,  // 6: hapi.annotations.is_type_of_response_code:extendee -> google.protobuf.EnumOptions
	10, // 7: hapi.annotations.response_code_value:extendee -> google.protobuf.EnumValueOptions
	11, // 8: hapi.annotations.method_extension_response_codes:extendee -> google.protobuf.FieldOptions
	2,  // 9: hapi.annotations.global_options:type_name -> hapi.annotations.GlobalOptions
	3,  // 10: hapi.annotations.method:type_name -> hapi.annotations.MethodOptions
	4,  // 11: hapi.annotations.response_code_value:type_name -> hapi.annotations.ResponseCodeValueOptions
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	9,  // [9:12] is the sub-list for extension type_name
	4,  // [4:9] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hapi_annotations_annotations_proto_init() }
func file_hapi_annotations_annotations_proto_init() {
	if File_hapi_annotations_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hapi_annotations_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hapi_annotations_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hapi_annotations_annotations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCodeValueOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hapi_annotations_annotations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalOptions_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hapi_annotations_annotations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalOptions_Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hapi_annotations_annotations_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MethodOptions_Get)(nil),
		(*MethodOptions_Post)(nil),
		(*MethodOptions_Delete)(nil),
		(*MethodOptions_Put)(nil),
		(*MethodOptions_Patch)(nil),
	}
	file_hapi_annotations_annotations_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ResponseCodeValueOptions_IsOk)(nil),
		(*ResponseCodeValueOptions_IsInvalidInput)(nil),
		(*ResponseCodeValueOptions_IsUnauthenticated)(nil),
		(*ResponseCodeValueOptions_IsServerError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hapi_annotations_annotations_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_hapi_annotations_annotations_proto_goTypes,
		DependencyIndexes: file_hapi_annotations_annotations_proto_depIdxs,
		EnumInfos:         file_hapi_annotations_annotations_proto_enumTypes,
		MessageInfos:      file_hapi_annotations_annotations_proto_msgTypes,
		ExtensionInfos:    file_hapi_annotations_annotations_proto_extTypes,
	}.Build()
	File_hapi_annotations_annotations_proto = out.File
	file_hapi_annotations_annotations_proto_rawDesc = nil
	file_hapi_annotations_annotations_proto_goTypes = nil
	file_hapi_annotations_annotations_proto_depIdxs = nil
}
