// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: hapi/annotations/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCodeLocation int32

const (
	ResponseCodeLocation_RESPONSE_CODE_LOCATION_BODY   ResponseCodeLocation = 0 // default
	ResponseCodeLocation_RESPONSE_CODE_LOCATION_HEADER ResponseCodeLocation = 1
)

// Enum value maps for ResponseCodeLocation.
var (
	ResponseCodeLocation_name = map[int32]string{
		0: "RESPONSE_CODE_LOCATION_BODY",
		1: "RESPONSE_CODE_LOCATION_HEADER",
	}
	ResponseCodeLocation_value = map[string]int32{
		"RESPONSE_CODE_LOCATION_BODY":   0,
		"RESPONSE_CODE_LOCATION_HEADER": 1,
	}
)

func (x ResponseCodeLocation) Enum() *ResponseCodeLocation {
	p := new(ResponseCodeLocation)
	*p = x
	return p
}

func (x ResponseCodeLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCodeLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_hapi_annotations_annotations_proto_enumTypes[0].Descriptor()
}

func (ResponseCodeLocation) Type() protoreflect.EnumType {
	return &file_hapi_annotations_annotations_proto_enumTypes[0]
}

func (x ResponseCodeLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCodeLocation.Descriptor instead.
func (ResponseCodeLocation) EnumDescriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

type AuthKind int32

const (
	AuthKind_AUTH_KIND_NONE             AuthKind = 0 // default
	AuthKind_AUTH_KIND_BEARER_IN_HEADER AuthKind = 1
)

// Enum value maps for AuthKind.
var (
	AuthKind_name = map[int32]string{
		0: "AUTH_KIND_NONE",
		1: "AUTH_KIND_BEARER_IN_HEADER",
	}
	AuthKind_value = map[string]int32{
		"AUTH_KIND_NONE":             0,
		"AUTH_KIND_BEARER_IN_HEADER": 1,
	}
)

func (x AuthKind) Enum() *AuthKind {
	p := new(AuthKind)
	*p = x
	return p
}

func (x AuthKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hapi_annotations_annotations_proto_enumTypes[1].Descriptor()
}

func (AuthKind) Type() protoreflect.EnumType {
	return &file_hapi_annotations_annotations_proto_enumTypes[1]
}

func (x AuthKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthKind.Descriptor instead.
func (AuthKind) EnumDescriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

type GlobalOptions struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ResponseCodeIn ResponseCodeLocation    `protobuf:"varint,1,opt,name=response_code_in,json=responseCodeIn,proto3,enum=hapi.annotations.ResponseCodeLocation" json:"response_code_in,omitempty"`
	AuthKind       AuthKind                `protobuf:"varint,2,opt,name=auth_kind,json=authKind,proto3,enum=hapi.annotations.AuthKind" json:"auth_kind,omitempty"`
	Info           *GlobalOptions_Info     `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Servers        []*GlobalOptions_Server `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalOptions) Reset() {
	*x = GlobalOptions{}
	mi := &file_hapi_annotations_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions) ProtoMessage() {}

func (x *GlobalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions.ProtoReflect.Descriptor instead.
func (*GlobalOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalOptions) GetResponseCodeIn() ResponseCodeLocation {
	if x != nil {
		return x.ResponseCodeIn
	}
	return ResponseCodeLocation_RESPONSE_CODE_LOCATION_BODY
}

func (x *GlobalOptions) GetAuthKind() AuthKind {
	if x != nil {
		return x.AuthKind
	}
	return AuthKind_AUTH_KIND_NONE
}

func (x *GlobalOptions) GetInfo() *GlobalOptions_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GlobalOptions) GetServers() []*GlobalOptions_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Route:
	//
	//	*MethodOptions_Get
	//	*MethodOptions_Post
	//	*MethodOptions_Delete
	//	*MethodOptions_Put
	//	*MethodOptions_Patch
	Route         isMethodOptions_Route `protobuf_oneof:"route"`
	SkipAuth      bool                  `protobuf:"varint,20,opt,name=skip_auth,json=skipAuth,proto3" json:"skip_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_hapi_annotations_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetRoute() isMethodOptions_Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *MethodOptions) GetGet() string {
	if x != nil {
		if x, ok := x.Route.(*MethodOptions_Get); ok {
			return x.Get
		}
	}
	return ""
}

func (x *MethodOptions) GetPost() string {
	if x != nil {
		if x, ok := x.Route.(*MethodOptions_Post); ok {
			return x.Post
		}
	}
	return ""
}

func (x *MethodOptions) GetDelete() string {
	if x != nil {
		if x, ok := x.Route.(*MethodOptions_Delete); ok {
			return x.Delete
		}
	}
	return ""
}

func (x *MethodOptions) GetPut() string {
	if x != nil {
		if x, ok := x.Route.(*MethodOptions_Put); ok {
			return x.Put
		}
	}
	return ""
}

func (x *MethodOptions) GetPatch() string {
	if x != nil {
		if x, ok := x.Route.(*MethodOptions_Patch); ok {
			return x.Patch
		}
	}
	return ""
}

func (x *MethodOptions) GetSkipAuth() bool {
	if x != nil {
		return x.SkipAuth
	}
	return false
}

type isMethodOptions_Route interface {
	isMethodOptions_Route()
}

type MethodOptions_Get struct {
	Get string `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type MethodOptions_Post struct {
	Post string `protobuf:"bytes,2,opt,name=post,proto3,oneof"`
}

type MethodOptions_Delete struct {
	Delete string `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type MethodOptions_Put struct {
	Put string `protobuf:"bytes,4,opt,name=put,proto3,oneof"`
}

type MethodOptions_Patch struct {
	Patch string `protobuf:"bytes,5,opt,name=patch,proto3,oneof"`
}

func (*MethodOptions_Get) isMethodOptions_Route() {}

func (*MethodOptions_Post) isMethodOptions_Route() {}

func (*MethodOptions_Delete) isMethodOptions_Route() {}

func (*MethodOptions_Put) isMethodOptions_Route() {}

func (*MethodOptions_Patch) isMethodOptions_Route() {}

type ResponseCodeValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Desc  string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	// Types that are valid to be assigned to Predefined:
	//
	//	*ResponseCodeValueOptions_IsOk
	//	*ResponseCodeValueOptions_IsInvalidInput
	//	*ResponseCodeValueOptions_IsUnauthenticated
	//	*ResponseCodeValueOptions_IsServerError
	Predefined    isResponseCodeValueOptions_Predefined `protobuf_oneof:"predefined"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCodeValueOptions) Reset() {
	*x = ResponseCodeValueOptions{}
	mi := &file_hapi_annotations_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCodeValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCodeValueOptions) ProtoMessage() {}

func (x *ResponseCodeValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCodeValueOptions.ProtoReflect.Descriptor instead.
func (*ResponseCodeValueOptions) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseCodeValueOptions) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ResponseCodeValueOptions) GetPredefined() isResponseCodeValueOptions_Predefined {
	if x != nil {
		return x.Predefined
	}
	return nil
}

func (x *ResponseCodeValueOptions) GetIsOk() bool {
	if x != nil {
		if x, ok := x.Predefined.(*ResponseCodeValueOptions_IsOk); ok {
			return x.IsOk
		}
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsInvalidInput() bool {
	if x != nil {
		if x, ok := x.Predefined.(*ResponseCodeValueOptions_IsInvalidInput); ok {
			return x.IsInvalidInput
		}
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsUnauthenticated() bool {
	if x != nil {
		if x, ok := x.Predefined.(*ResponseCodeValueOptions_IsUnauthenticated); ok {
			return x.IsUnauthenticated
		}
	}
	return false
}

func (x *ResponseCodeValueOptions) GetIsServerError() bool {
	if x != nil {
		if x, ok := x.Predefined.(*ResponseCodeValueOptions_IsServerError); ok {
			return x.IsServerError
		}
	}
	return false
}

type isResponseCodeValueOptions_Predefined interface {
	isResponseCodeValueOptions_Predefined()
}

type ResponseCodeValueOptions_IsOk struct {
	IsOk bool `protobuf:"varint,10,opt,name=is_ok,json=isOk,proto3,oneof"`
}

type ResponseCodeValueOptions_IsInvalidInput struct {
	IsInvalidInput bool `protobuf:"varint,11,opt,name=is_invalid_input,json=isInvalidInput,proto3,oneof"`
}

type ResponseCodeValueOptions_IsUnauthenticated struct {
	IsUnauthenticated bool `protobuf:"varint,12,opt,name=is_unauthenticated,json=isUnauthenticated,proto3,oneof"`
}

type ResponseCodeValueOptions_IsServerError struct {
	IsServerError bool `protobuf:"varint,13,opt,name=is_server_error,json=isServerError,proto3,oneof"`
}

func (*ResponseCodeValueOptions_IsOk) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsInvalidInput) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsUnauthenticated) isResponseCodeValueOptions_Predefined() {}

func (*ResponseCodeValueOptions_IsServerError) isResponseCodeValueOptions_Predefined() {}

type GlobalOptions_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalOptions_Info) Reset() {
	*x = GlobalOptions_Info{}
	mi := &file_hapi_annotations_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalOptions_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions_Info) ProtoMessage() {}

func (x *GlobalOptions_Info) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions_Info.ProtoReflect.Descriptor instead.
func (*GlobalOptions_Info) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GlobalOptions_Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GlobalOptions_Info) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GlobalOptions_Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalOptions_Server) Reset() {
	*x = GlobalOptions_Server{}
	mi := &file_hapi_annotations_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalOptions_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions_Server) ProtoMessage() {}

func (x *GlobalOptions_Server) ProtoReflect() protoreflect.Message {
	mi := &file_hapi_annotations_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalOptions_Server.ProtoReflect.Descriptor instead.
func (*GlobalOptions_Server) Descriptor() ([]byte, []int) {
	return file_hapi_annotations_annotations_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GlobalOptions_Server) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var file_hapi_annotations_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GlobalOptions)(nil),
		Field:         71620996,
		Name:          "hapi.annotations.global_options",
		Tag:           "bytes,71620996,opt,name=global_options",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         87040365,
		Name:          "hapi.annotations.method",
		Tag:           "bytes,87040365,opt,name=method",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         17916130,
		Name:          "hapi.annotations.is_type_of_response_code",
		Tag:           "varint,17916130,opt,name=is_type_of_response_code",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ResponseCodeValueOptions)(nil),
		Field:         33878095,
		Name:          "hapi.annotations.response_code_value",
		Tag:           "bytes,33878095,opt,name=response_code_value",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         43713190,
		Name:          "hapi.annotations.method_extension_response_codes",
		Tag:           "varint,43713190,opt,name=method_extension_response_codes",
		Filename:      "hapi/annotations/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         10679595,
		Name:          "hapi.annotations.no_go_omitempty_tag",
		Tag:           "varint,10679595,opt,name=no_go_omitempty_tag",
		Filename:      "hapi/annotations/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional hapi.annotations.GlobalOptions global_options = 71620996;
	E_GlobalOptions = &file_hapi_annotations_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional hapi.annotations.MethodOptions method = 87040365;
	E_Method = &file_hapi_annotations_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional bool is_type_of_response_code = 17916130;
	E_IsTypeOfResponseCode = &file_hapi_annotations_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional hapi.annotations.ResponseCodeValueOptions response_code_value = 33878095;
	E_ResponseCodeValue = &file_hapi_annotations_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool method_extension_response_codes = 43713190;
	E_MethodExtensionResponseCodes = &file_hapi_annotations_annotations_proto_extTypes[4]
	// optional bool no_go_omitempty_tag = 10679595;
	E_NoGoOmitemptyTag = &file_hapi_annotations_annotations_proto_extTypes[5]
)

var File_hapi_annotations_annotations_proto protoreflect.FileDescriptor

const file_hapi_annotations_annotations_proto_rawDesc = "" +
	"\n" +
	"\"hapi/annotations/annotations.proto\x12\x10hapi.annotations\x1a google/protobuf/descriptor.proto\"\xea\x02\n" +
	"\rGlobalOptions\x12P\n" +
	"\x10response_code_in\x18\x01 \x01(\x0e2&.hapi.annotations.ResponseCodeLocationR\x0eresponseCodeIn\x127\n" +
	"\tauth_kind\x18\x02 \x01(\x0e2\x1a.hapi.annotations.AuthKindR\bauthKind\x128\n" +
	"\x04info\x18\x03 \x01(\v2$.hapi.annotations.GlobalOptions.InfoR\x04info\x12@\n" +
	"\aservers\x18\x04 \x03(\v2&.hapi.annotations.GlobalOptions.ServerR\aservers\x1a6\n" +
	"\x04Info\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x1a\x1a\n" +
	"\x06Server\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa5\x01\n" +
	"\rMethodOptions\x12\x12\n" +
	"\x03get\x18\x01 \x01(\tH\x00R\x03get\x12\x14\n" +
	"\x04post\x18\x02 \x01(\tH\x00R\x04post\x12\x18\n" +
	"\x06delete\x18\x03 \x01(\tH\x00R\x06delete\x12\x12\n" +
	"\x03put\x18\x04 \x01(\tH\x00R\x03put\x12\x16\n" +
	"\x05patch\x18\x05 \x01(\tH\x00R\x05patch\x12\x1b\n" +
	"\tskip_auth\x18\x14 \x01(\bR\bskipAuthB\a\n" +
	"\x05route\"\xda\x01\n" +
	"\x18ResponseCodeValueOptions\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12\x15\n" +
	"\x05is_ok\x18\n" +
	" \x01(\bH\x00R\x04isOk\x12*\n" +
	"\x10is_invalid_input\x18\v \x01(\bH\x00R\x0eisInvalidInput\x12/\n" +
	"\x12is_unauthenticated\x18\f \x01(\bH\x00R\x11isUnauthenticated\x12(\n" +
	"\x0fis_server_error\x18\r \x01(\bH\x00R\risServerErrorB\f\n" +
	"\n" +
	"predefined*Z\n" +
	"\x14ResponseCodeLocation\x12\x1f\n" +
	"\x1bRESPONSE_CODE_LOCATION_BODY\x10\x00\x12!\n" +
	"\x1dRESPONSE_CODE_LOCATION_HEADER\x10\x01*>\n" +
	"\bAuthKind\x12\x12\n" +
	"\x0eAUTH_KIND_NONE\x10\x00\x12\x1e\n" +
	"\x1aAUTH_KIND_BEARER_IN_HEADER\x10\x01:g\n" +
	"\x0eglobal_options\x12\x1c.google.protobuf.FileOptions\x18\x84\xb3\x93\" \x01(\v2\x1f.hapi.annotations.GlobalOptionsR\rglobalOptions:Z\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xed\xc2\xc0) \x01(\v2\x1f.hapi.annotations.MethodOptionsR\x06method:W\n" +
	"\x18is_type_of_response_code\x12\x1c.google.protobuf.EnumOptions\x18\xe2\xc1\xc5\b \x01(\bR\x14isTypeOfResponseCode:\x80\x01\n" +
	"\x13response_code_value\x12!.google.protobuf.EnumValueOptions\x18\xcf\xe0\x93\x10 \x01(\v2*.hapi.annotations.ResponseCodeValueOptionsR\x11responseCodeValue:g\n" +
	"\x1fmethod_extension_response_codes\x12\x1d.google.protobuf.FieldOptions\x18\xa6\x85\xec\x14 \x01(\bR\x1cmethodExtensionResponseCodes:O\n" +
	"\x13no_go_omitempty_tag\x12\x1d.google.protobuf.FieldOptions\x18\xab\xea\x8b\x05 \x01(\bR\x10noGoOmitemptyTagB2Z0github.com/paleviews/hapi/descriptor/annotationsb\x06proto3"

var (
	file_hapi_annotations_annotations_proto_rawDescOnce sync.Once
	file_hapi_annotations_annotations_proto_rawDescData []byte
)

func file_hapi_annotations_annotations_proto_rawDescGZIP() []byte {
	file_hapi_annotations_annotations_proto_rawDescOnce.Do(func() {
		file_hapi_annotations_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hapi_annotations_annotations_proto_rawDesc), len(file_hapi_annotations_annotations_proto_rawDesc)))
	})
	return file_hapi_annotations_annotations_proto_rawDescData
}

var file_hapi_annotations_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hapi_annotations_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hapi_annotations_annotations_proto_goTypes = []any{
	(ResponseCodeLocation)(0),             // 0: hapi.annotations.ResponseCodeLocation
	(AuthKind)(0),                         // 1: hapi.annotations.AuthKind
	(*GlobalOptions)(nil),                 // 2: hapi.annotations.GlobalOptions
	(*MethodOptions)(nil),                 // 3: hapi.annotations.MethodOptions
	(*ResponseCodeValueOptions)(nil),      // 4: hapi.annotations.ResponseCodeValueOptions
	(*GlobalOptions_Info)(nil),            // 5: hapi.annotations.GlobalOptions.Info
	(*GlobalOptions_Server)(nil),          // 6: hapi.annotations.GlobalOptions.Server
	(*descriptorpb.FileOptions)(nil),      // 7: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),    // 8: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),      // 9: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 10: google.protobuf.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),     // 11: google.protobuf.FieldOptions
}
var file_hapi_annotations_annotations_proto_depIdxs = []int32{
	0,  // 0: hapi.annotations.GlobalOptions.response_code_in:type_name -> hapi.annotations.ResponseCodeLocation
	1,  // 1: hapi.annotations.GlobalOptions.auth_kind:type_name -> hapi.annotations.AuthKind
	5,  // 2: hapi.annotations.GlobalOptions.info:type_name -> hapi.annotations.GlobalOptions.Info
	6,  // 3: hapi.annotations.GlobalOptions.servers:type_name -> hapi.annotations.GlobalOptions.Server
	7,  // 4: hapi.annotations.global_options:extendee -> google.protobuf.FileOptions
	8,  // 5: hapi.annotations.method:extendee -> google.protobuf.MethodOptions
	9,  // 6: hapi.annotations.is_type_of_response_code:extendee -> google.protobuf.EnumOptions
	10, // 7: hapi.annotations.response_code_value:extendee -> google.protobuf.EnumValueOptions
	11, // 8: hapi.annotations.method_extension_response_codes:extendee -> google.protobuf.FieldOptions
	11, // 9: hapi.annotations.no_go_omitempty_tag:extendee -> google.protobuf.FieldOptions
	2,  // 10: hapi.annotations.global_options:type_name -> hapi.annotations.GlobalOptions
	3,  // 11: hapi.annotations.method:type_name -> hapi.annotations.MethodOptions
	4,  // 12: hapi.annotations.response_code_value:type_name -> hapi.annotations.ResponseCodeValueOptions
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	10, // [10:13] is the sub-list for extension type_name
	4,  // [4:10] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hapi_annotations_annotations_proto_init() }
func file_hapi_annotations_annotations_proto_init() {
	if File_hapi_annotations_annotations_proto != nil {
		return
	}
	file_hapi_annotations_annotations_proto_msgTypes[1].OneofWrappers = []any{
		(*MethodOptions_Get)(nil),
		(*MethodOptions_Post)(nil),
		(*MethodOptions_Delete)(nil),
		(*MethodOptions_Put)(nil),
		(*MethodOptions_Patch)(nil),
	}
	file_hapi_annotations_annotations_proto_msgTypes[2].OneofWrappers = []any{
		(*ResponseCodeValueOptions_IsOk)(nil),
		(*ResponseCodeValueOptions_IsInvalidInput)(nil),
		(*ResponseCodeValueOptions_IsUnauthenticated)(nil),
		(*ResponseCodeValueOptions_IsServerError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hapi_annotations_annotations_proto_rawDesc), len(file_hapi_annotations_annotations_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_hapi_annotations_annotations_proto_goTypes,
		DependencyIndexes: file_hapi_annotations_annotations_proto_depIdxs,
		EnumInfos:         file_hapi_annotations_annotations_proto_enumTypes,
		MessageInfos:      file_hapi_annotations_annotations_proto_msgTypes,
		ExtensionInfos:    file_hapi_annotations_annotations_proto_extTypes,
	}.Build()
	File_hapi_annotations_annotations_proto = out.File
	file_hapi_annotations_annotations_proto_goTypes = nil
	file_hapi_annotations_annotations_proto_depIdxs = nil
}
