// Code generated by proto-gen-hapi. DO NOT EDIT.
// version:
// - protoc-gen-hapi v0.1.0
// - protoc          v3.21.8
// source: todo/model.proto

package todo

type Todo struct {
	// 分配的 ID
	ID     int64             `json:"ID,omitempty"`
	Title  string            `json:"title,omitempty"`
	Detail string            `json:"detail,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// 完成程度，取值范围 [0, 100]
	Completeness  int32 `json:"completeness,omitempty"`
	CreatedTime   int64 `json:"created_time,omitempty"`
	CompletedTime int64 `json:"completed_time,omitempty"`
}
