// Code generated by proto-gen-hapi. DO NOT EDIT.
// version:
// - protoc-gen-hapi v0.1.0
// - protoc          v3.21.12
// source: todo/model.proto

package todo

type Todo struct {
	// 分配的 ID
	ID     int64             `json:"ID,omitempty"`
	Title  string            `json:"title,omitempty"`
	Detail string            `json:"detail,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// 完成程度，取值范围 [0, 100]
	Completeness  int32 `json:"completeness,omitempty"`
	CreatedTime   int64 `json:"created_time,omitempty"`
	CompletedTime int64 `json:"completed_time,omitempty"`
}

func (x *Todo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}
func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}
func (x *Todo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}
func (x *Todo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}
func (x *Todo) GetCompleteness() int32 {
	if x != nil {
		return x.Completeness
	}
	return 0
}
func (x *Todo) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}
func (x *Todo) GetCompletedTime() int64 {
	if x != nil {
		return x.CompletedTime
	}
	return 0
}
