// Code generated by proto-gen-hapi. DO NOT EDIT.
// version:
// - protoc-gen-hapi v0.1.0
// - protoc          v7.34.1
// source: codes/response_code.proto

package codes

import (
	context "context"
	runtime "github.com/paleviews/hapi/runtime"
	sync "sync"
)

type ResponseCode = runtime.ResponseCode

const (
	// just ok
	ResponseCode_RESPONSE_CODE_OK              ResponseCode = 0
	ResponseCode_RESPONSE_CODE_INVALID_INPUT   ResponseCode = 1
	ResponseCode_RESPONSE_CODE_UNAUTHENTICATED ResponseCode = 2
	ResponseCode_RESPONSE_CODE_SERVER_ERROR    ResponseCode = 99
	ResponseCode_RESPONSE_CODE_UNIMPLEMENTED   ResponseCode = 1001
)

func GetDescByResponseCode(code ResponseCode) string {
	switch code {
	case ResponseCode_RESPONSE_CODE_OK:
		return "ok"
	case ResponseCode_RESPONSE_CODE_INVALID_INPUT:
		return "invalid_input"
	case ResponseCode_RESPONSE_CODE_UNAUTHENTICATED:
		return "unauthenticated"
	case ResponseCode_RESPONSE_CODE_SERVER_ERROR:
		return "server_error"
	case ResponseCode_RESPONSE_CODE_UNIMPLEMENTED:
		return "unimplemented"
	default:
		return ""
	}
}

type ToError func(ctx context.Context, code ResponseCode, src error) runtime.APIError

var (
	apiErrorFromResponseCode ToError
	setOnce                  sync.Once
)

func SetToErrorFunc(f ToError) {
	if f == nil {
		return
	}
	setOnce.Do(func() {
		apiErrorFromResponseCode = f
	})
}

func DescFromResponseCode(ctx context.Context, code ResponseCode) string {
	if f := apiErrorFromResponseCode; f != nil {
		return f(ctx, code, nil).Message
	}
	return GetDescByResponseCode(code)
}

func APIErrorFromResponseCode(ctx context.Context, code ResponseCode, src error) runtime.APIError {
	if f := apiErrorFromResponseCode; f != nil {
		return f(ctx, code, src)
	}
	return runtime.NewAPIError(code, GetDescByResponseCode(code), src)
}
